application:
  port: 8000
  host: 127.0.0.1
database:
  port: 5432
  host: "localhost"
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@example.com"
  authorization_token: "my-secret-token"
